import type { CafeCategory, CafeProduct } from './types'

export const DEFAULT_CAFE_CATEGORIES: CafeCategory[] = [
  { id: 'cat-togo', name: 'TO-GO', icon: '🥤', sort_order: 1, is_active: true },
  { id: 'cat-espresso', name: 'ESPRESSO', icon: '☕', sort_order: 2, is_active: true },
  { id: 'cat-milk', name: 'MILK', icon: '🥛', sort_order: 3, is_active: true },
  { id: 'cat-refresher', name: 'REFRESHER', icon: '🍋', sort_order: 4, is_active: true },
  { id: 'cat-dessert', name: 'DESSERT', icon: '🍰', sort_order: 5, is_active: true },
]

export const DEFAULT_CAFE_PRODUCTS: CafeProduct[] = [
  // ─── TO-GO (Botol 250ml) ─────────────────────────────────
  {
    id: 'prod-botol-ks',
    category_id: 'cat-togo',
    name: 'Kopi Susu Botol',
    description: 'Kopi susu gula aren signature Méra Hause kemasan botol siap minum 250ml',
    price: 23000,
    cost_price: 9764,
    is_available: true,
    sort_order: 1,
  },
  {
    id: 'prod-botol-bs',
    category_id: 'cat-togo',
    name: 'Butterscotch Botol',
    description: 'Kopi susu butterscotch creamy gurih botol 250ml',
    price: 23000,
    cost_price: 10966,
    is_available: true,
    sort_order: 2,
  },
  {
    id: 'prod-botol-gt',
    category_id: 'cat-togo',
    name: 'Green Tea Latte Botol',
    description: 'Matcha green tea latte creamy botol 250ml',
    price: 23000,
    cost_price: 11498,
    is_available: true,
    sort_order: 3,
  },

  // ─── ESPRESSO ────────────────────────────────────────────
  {
    id: 'prod-esprs-ks',
    category_id: 'cat-espresso',
    name: 'Kopi Susu',
    description: 'Signature kopi susu gula aren Méra Hause',
    price: 23000,
    cost_price: 7915,
    is_available: true,
    sort_order: 4,
  },
  {
    id: 'prod-esprs-bs',
    category_id: 'cat-espresso',
    name: 'Butterscotch',
    description: 'Espresso dengan paduan butterscotch manis gurih lembut',
    price: 23000,
    cost_price: 10872,
    is_available: true,
    sort_order: 5,
  },
  {
    id: 'prod-esprs-tr',
    category_id: 'cat-espresso',
    name: 'Tiramisu',
    description: 'Espresso dengan rasa tiramisu khas Italia',
    price: 23000,
    cost_price: 10724,
    is_available: true,
    sort_order: 6,
  },
  {
    id: 'prod-esprs-am',
    category_id: 'cat-espresso',
    name: 'Americano',
    description: 'Double shot espresso dengan air dingin/panas segar',
    price: 23000,
    cost_price: 5992,
    is_available: true,
    sort_order: 7,
  },
  {
    id: 'prod-esprs-mr',
    category_id: 'cat-espresso',
    name: 'Meraricano',
    description: 'Signature Americano Méra dengan twist buah segar',
    price: 23000,
    cost_price: 8362,
    is_available: true,
    sort_order: 8,
  },

  // ─── MILK ────────────────────────────────────────────────
  {
    id: 'prod-milk-gt',
    category_id: 'cat-milk',
    name: 'Green Tea Latte',
    description: 'Pure matcha dipadu susu segar lembut',
    price: 23000,
    cost_price: 7732,
    is_available: true,
    sort_order: 9,
  },
  {
    id: 'prod-milk-cb',
    category_id: 'cat-milk',
    name: 'Choco Berries',
    description: 'Cokelat kaya rasa dengan sentuhan buah beri segar',
    price: 23000,
    cost_price: 12709,
    is_available: true,
    sort_order: 10,
  },
  {
    id: 'prod-milk-cp',
    category_id: 'cat-milk',
    name: 'Choco Pistachio',
    description: 'Cokelat premium dengan aroma kacang pistachio gurih',
    price: 23000,
    cost_price: 8976,
    is_available: true,
    sort_order: 11,
  },
  {
    id: 'prod-milk-bs',
    category_id: 'cat-milk',
    name: 'Blueberry Sundae',
    description: 'Minuman susu creamy dengan selai blueberry segar',
    price: 23000,
    cost_price: 7327,
    is_available: true,
    sort_order: 12,
  },
  {
    id: 'prod-milk-sb',
    category_id: 'cat-milk',
    name: 'Sakura Blossoms',
    description: 'Susu wangi bunga sakura manis lembut menyegarkan',
    price: 23000,
    cost_price: 6178,
    is_available: true,
    sort_order: 13,
  },

  // ─── REFRESHER ───────────────────────────────────────────
  {
    id: 'prod-refrs-gl',
    category_id: 'cat-refresher',
    name: 'Green Limuna',
    description: 'Mocktail segar sari jeruk nipis & herba mint',
    price: 20000,
    cost_price: 4645,
    is_available: true,
    sort_order: 14,
  },
  {
    id: 'prod-refrs-bp',
    category_id: 'cat-refresher',
    name: 'Bloomy Peachy',
    description: 'Kombinasi teh buah persik peach manis & bunga mekar',
    price: 20000,
    cost_price: 5149,
    is_available: true,
    sort_order: 15,
  },
  {
    id: 'prod-refrs-bt',
    category_id: 'cat-refresher',
    name: 'Blueberry Tea',
    description: 'Teh harum rasa buah blueberry segar dingin',
    price: 18000,
    cost_price: 4504,
    is_available: true,
    sort_order: 16,
  },
  {
    id: 'prod-refrs-lm',
    category_id: 'cat-refresher',
    name: 'Lemon Tea',
    description: 'Teh sari lemon segar dingin penyegar dahaga',
    price: 18000,
    cost_price: 2560,
    is_available: true,
    sort_order: 17,
  },
  {
    id: 'prod-refrs-ly',
    category_id: 'cat-refresher',
    name: 'Lychee Tea',
    description: 'Teh leci wangi dengan rasa manis buah leci asli',
    price: 18000,
    cost_price: 4276,
    is_available: true,
    sort_order: 18,
  },
  {
    id: 'prod-refrs-st',
    category_id: 'cat-refresher',
    name: 'Strawberry Tea',
    description: 'Teh stroberi manis asam segar dingin',
    price: 18000,
    cost_price: 4275,
    is_available: true,
    sort_order: 19,
  },

  // ─── DESSERT ─────────────────────────────────────────────
  {
    id: 'prod-dssrt-bcc',
    category_id: 'cat-dessert',
    name: 'Blueberry Cheese Cake',
    description: 'Kue keju lembut premium dengan topping selai blueberry',
    price: 28000,
    cost_price: 15938,
    is_available: true,
    sort_order: 20,
  },
  {
    id: 'prod-dssrt-lcc',
    category_id: 'cat-dessert',
    name: 'London Choco Cake',
    description: 'Rich dark chocolate cake khas London yang lumer',
    price: 38000,
    cost_price: 21250,
    is_available: true,
    sort_order: 21,
  },
  {
    id: 'prod-dssrt-trt',
    category_id: 'cat-dessert',
    name: 'Tiramisu Tart',
    description: 'Tart renyah dengan isian cream tiramisu kopi otentik',
    price: 38000,
    cost_price: 23800,
    is_available: true,
    sort_order: 22,
  },
  {
    id: 'prod-dssrt-mmo',
    category_id: 'cat-dessert',
    name: 'Meramisu Original',
    description: 'Signature Meramisu cake cup lembut racikan Méra Hause',
    price: 28000,
    cost_price: 8267,
    is_available: true,
    sort_order: 23,
  },
  {
    id: 'prod-dssrt-mmb',
    category_id: 'cat-dessert',
    name: 'Meramisu Blueberry',
    description: 'Signature Meramisu dipadu kesegaran buah blueberry',
    price: 28000,
    cost_price: 11517,
    is_available: true,
    sort_order: 24,
  },
  {
    id: 'prod-dssrt-mmbs',
    category_id: 'cat-dessert',
    name: 'Meramisu Biscoff',
    description: 'Signature Meramisu dengan selai dan remah lotus biscoff',
    price: 28000,
    cost_price: 12100,
    is_available: true,
    sort_order: 25,
  },
]
